# Settings for mkdocs

# Where to find documentation
docs_dir: docs

# Link to Github on every page
repo_url: https://github.com/openfoodfacts/openfoodfacts-server
edit_uri: blob/main/docs/
# add canonical url
site_url: https://openfoodfacts.github.io/openfoodfacts-server/

site_name: Product Opener (Open Food Facts Server)
site_dir: gh_pages

theme:
  name: material

markdown_extensions:
  - footnotes
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - awesome-pages
  - search
