type: object
description: |
  Quantity of a nutrient

  (per 100g, per 100ml or per serving) in a standard unit (g or ml)
properties:
  value:
    type: number
    description: |
      A normalized float value for the quantity, computed from `value_string` if it exists.
    examples:
      - 2
      - 4.1
  unit:
    type: string
    description: |
        The unit of the value entered by the contributor (a user or the manufacturer), for the product.
        In most cases, this unit is the unit displayed on the product for the nutrient, but it is not guaranteed, as some apps may force specific units when writing nutrient values.          

        The possible values depends on the nutrient.

        * `g` for grams
        * `mg` for milligrams
        * `Œºg` for micrograms
        * `cl` for centiliters
        * `ml` for mililiters
        * `dv` for recommended daily intakes (aka [Dietary Reference Intake](https://en.wikipedia.org/wiki/Dietary_Reference_Intake))
        * `% vol` for alcohol vol per 100 ml

        ü§ì code: see the [Units module][units-module],
        and [Food:default_unit_for_nid function][default-unit]

        [units-module]: https://openfoodfacts.github.io/openfoodfacts-server/dev/ref-perl-pod/ProductOpener/Units.html
        [default-unit]: https://openfoodfacts.github.io/openfoodfacts-server/dev/ref-perl-pod/ProductOpener/Food.html#default_unit_for_nid_(_%24nid)
    examples:
      [
        "ÂÖ¨Êñ§",
        "ÂÖ¨Âçá",
        "kg",
        "–∫–≥",
        "l",
        "–ª",
        "ÊØ´ÂÖã",
        "mg",
        "–º–≥",
        "mcg",
        "¬µg",
        "oz",
        "fl oz",
        "dl",
        "–¥–ª",
        "cl",
        "–∫–ª",
        "Êñ§",
        "g",
        "",
        " ",
        "kJ",
        "ÂÖã",
        "ÂÖ¨ÂÖã",
        "–≥",
        "–º–ª",
        "ml",
        "mmol/l",
        "ÊØ´Âçá",
        "% vol",
        "ph",
        "%",
        "% dv",
        "% vol (alcohol)",
        "iu",
        "mol/l",
        "mval/l",
        "ppm",
        "ÔøΩrh",
        "ÔøΩfh",
        "ÔøΩe",
        "ÔøΩdh",
        "gpg",
      ]
  modifier:
    type: string
    enum: ["<", "<=", "~", ">=", ">"]
    description: |
      This property is optional.