version: "3.7"
services:
  mongoku:
    image: huggingface/mongoku:1.3.0
    depends_on:
      - mongodb
    ports:
      - ${ADMIN_EXPOSE}8080:8080
    environment:
      - MONGOKU_DEFAULT_HOST=mongodb://mongodb:27017
      - MONGOKU_SERVER_PORT=8080
  phpmemcachedadmin:
    image: moonbuggy2000/phpmemcachedadmin:1.3.0
    depends_on:
      - memcached
    ports:
      - ${ADMIN_EXPOSE}8081:8080
  adminer:
    image: adminer:4-standalone
    depends_on:
      - postgres
    ports:
      - ${ADMIN_EXPOSE}8082:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres
