version: "3.7"
services:
  backend:
    volumes:
      - type: bind
        source: ./backend-dev/conf/Config2.pm
        target: /opt/product-opener/lib/ProductOpener/Config2.pm
      - type: bind
        source: ./backend-dev/scripts/
        target: /opt/scripts/
      # Data mount for Robotoff static data dumps:
      # - openfoodfacts-products.jsonl.gz
      # - categories.full.json
      # - ingredients.full.json
      # - labels.full.json
      # - brands.full.json
      - type: bind
        source: /mnt/data/
        target: /opt/product-opener/html/data
