version: "3.3"
services:
  mongodb:
    image: mongo:latest
    volumes:
      - dbdata:/var/lib/mongodb
    ports:
      - 27017:27017
    networks:
      - webnet
  backend:
    image: productopener/backend-git:latest
    depends_on:
      - mongodb
    volumes:
      - podata:/mnt/podata
      - product_images:/opt/product-opener/html/images/products
    configs:
      - source: poconfig
        target: /opt/product-opener/lib/ProductOpener/Config.pm
      - source: poconfig2
        target: /opt/product-opener/lib/ProductOpener/Config2.pm
      - source: apacheconfig
        target: /usr/local/apache2/conf/sites-enabled/product-opener.conf
      - source: starthttpd
        target: /usr/local/bin/po-foreground.sh
    command: ["/bin/sh", "/usr/local/bin/po-foreground.sh"]
    ports:
      - 80
    networks:
      - webnet
  frontend:
    image: productopener/frontend-git:latest
    depends_on:
      - backend
    volumes:
      - product_images:/opt/product-opener/html/images/products
    configs:
      - source: nginxconfig
        target: /etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - webnet
networks:
  webnet:
volumes:
  dbdata:
  podata:
  product_images:
configs:
  poconfig:
    file: ./backend-git/conf/Config.pm
  poconfig2:
    file: ./backend-git/conf/Config2.pm
  apacheconfig:
    file: ./backend-git/conf/apache.conf
  starthttpd:
    file: ./backend-git/conf/po-foreground.sh
  nginxconfig:
    file: ./frontend-git/conf/nginx.conf
