# Referenced when running locally

services:
  frontend:
    networks:
      # Needed to access OTel collector
      shared_network:
  backend:
    networks:
      # Needed to access MongoDB, Redis, and OTel collector
      shared_network:
  minion:
    networks:
      # Needed to access MongoDB, Redis, and OTel collector
      shared_network:

networks:
  # This network allows access to shared services like MongoDB and Redis
  shared_network:
    name: ${COMMON_NET_NAME}
    external: true
