name: Ventilate issues to the right GitHub projects

on:
  issues:
    types:
      - labeled
      - opened
      - transferred

jobs:
  add-to-projects:
    name: Ventilate issues to the right GitHub projects
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/openfoodfacts/projects/43 # Add issue to the openfoodfacts-design project
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: üé® Mockup available, üé® Mockup required
          label-operator: OR
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/openfoodfacts/projects/36 # Add issue to the open pet food facts project
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: üêæ Open Pet Food Facts
          label-operator: OR
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/openfoodfacts/projects/11 # Add issue to the open products facts project
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: üì∏ Open Products Facts
          label-operator: OR
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/openfoodfacts/projects/37 # Add issue to the open beauty facts project
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: üß¥ Open Beauty Facts
          label-operator: OR
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/openfoodfacts/projects/4 # Add issue to the packaging project
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: üì¶ Packaging
          label-operator: OR
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/openfoodfacts/projects/25 # Add issue to the documentation project
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: üìö Documentation
          label-operator: OR
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/openfoodfacts/projects/5 # Add issue to the folksonomy project
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: üè∑Ô∏è Folksonomy Project
          label-operator: OR         
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/openfoodfacts/projects/44 # Add issue to the data quality project
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: üßΩ Data quality
          label-operator: OR    
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/openfoodfacts/projects/82 # Add issue to the search project
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: üîé Search
          label-operator: OR
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/openfoodfacts/projects/41 # Add issue to the producer platform project
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: üè≠ Producers Platform
          label-operator: OR    
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/openfoodfacts/projects/19 # Add issue to the infrastructure project
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: infrastructure
          label-operator: OR   
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/openfoodfacts/projects/92 # Add issue to the Nutri-Score project
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: üö¶ Nutri-Score
          label-operator: OR   
