name: Perl Critic

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  perlcritic:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Perl Critic
      uses: Difegue/action-perlcritic@2.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: cgi/*.pl scripts/*.pl lib/ProductOpener/*.pm lib/*.pl t/*.t
